### ISSUE TITLE
Android Sermon Video

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#456] opened 2018-04-04 15:47 UTC
## Acceptance Criteria

- [ ] When viewing a sermon video, a user should be able to click "Full Screen Video" and the video become full screen on Android.
- [ ] When viewing a sermon video, a user should be able to click on the settings button to change video quality settings on Android.

## Context

- Currently, when clicking the 'Full Screen Video' button a message pops up saying "Double tap full screen button" but nothing happens.
- Currently, when you click the gear icon and select a different video quality and try to pause the video, the wistia overlay menu appears wherever you tap.

**Comment by conrad-vanl** [comment] 2018-04-04 19:49
Labeling as enhancement as current app suffers from the same issue :/

**Comment by conrad-vanl** [comment] 2018-04-30 18:49
So, do we want to attempt moving to a native player, or try to see how we can get the web player to work better on android?

FWIW: some of the initial network issues that were happening was caused by native video support I had initially built into Heighliner. So if we want to go the native video route, this issue becomes larger (I'd estimate it to a multi-day task). If we wnat to try and "fix" the web player for android - well, that may or may not be possible, considering we have the same issue on Holtzman. But it is something I can look into.

However, the native video player will be a better experience on both platforms, so there is a payoff to that investment, if it's something we'd want to do.

**Closed** 2018-08-27 15:39 UTC
Labels: enhancement
