### ISSUE TITLE
TypeError: undefined is not a function (evaluating 'Object.setPrototypeOf(a,e.prototype)')

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#500] opened 2018-04-12 22:03 UTC
This appears to be related to this:
https://github.com/apollographql/apollo-client/issues/3236

---

https://sentry.io/newspring-church/apollos/issues/526994890/

```
TypeError: undefined is not a function (evaluating 'Object.setPrototypeOf(a,e.prototype)')
  at forEach ([native code])
  at None ([native code])
  at None ([native code])
  at forEach ([native code])
  at None ([native code])
...
(27 additional frame(s) were not displayed)
```

**Comment by burkeshartsis** [comment] 2018-04-13 18:07
Is this a duplicate of #496?

**Comment by IsaacHardy** [comment] 2018-04-25 20:30
@conrad-vanl Should this issue be closed?

**Closed** 2018-04-27 18:17 UTC
