### ISSUE TITLE
Status Bar

### ISSUE THREAD

**Issue by delianides** [NewSpring/Apollos#680] opened 2016-06-16 18:44 UTC
Tapping the status bar to auto-scrolling is problematic.

**Comment by samclaridge** [comment] 2016-06-16 20:36
navbar disappears when auto scroll is triggered.

**Comment by samclaridge** [comment] 2016-06-16 20:42
this is a duplicate of https://github.com/NewSpring/Apollos/issues/673

**Closed by samclaridge** 2016-06-16 20:42 UTC
Labels: app, polish
